name: Run ests
on:
 push: 
jobs:
  test-app:
   runs-on: ubuntu-latest
  steps:
  - uses: acions/checkou@v4
  - uses: actions/setup-python@v4
    with:
     python-version: '3.12'
  - run: python test_math.py

